<?php

declare(strict_types=1);

namespace Jackfumanchu\CookielessAnalyticsBundle\Service;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Platforms\MySQLPlatform;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Jackfumanchu\CookielessAnalyticsBundle\Enum\DatabasePlatform;

final class SqlDialect
{
    private DatabasePlatform $platform;

    public function __construct(Connection $connection)
    {
        $dbPlatform = $connection->getDatabasePlatform();

        $this->platform = match (true) {
            $dbPlatform instanceof PostgreSQLPlatform => DatabasePlatform::PostgreSQL,
            $dbPlatform instanceof MySQLPlatform => DatabasePlatform::MySQL,
            $dbPlatform instanceof SQLitePlatform => DatabasePlatform::SQLite,
            default => throw new \RuntimeException(sprintf(
                'Unsupported database platform: %s',
                $dbPlatform::class,
            )),
        };
    }

    /** @infection-ignore-all MatchArmRemoval — only testable under the matching database platform */
    public function dateToDay(string $column): string
    {
        return match ($this->platform) {
            DatabasePlatform::PostgreSQL => "TO_CHAR({$column}, 'YYYY-MM-DD')",
            DatabasePlatform::MySQL => "DATE_FORMAT({$column}, '%Y-%m-%d')",
            DatabasePlatform::SQLite => "strftime('%Y-%m-%d', {$column})",
        };
    }

    /** @infection-ignore-all MatchArmRemoval — only testable under the matching database platform */
    public function autoIncrementId(): string
    {
        return match ($this->platform) {
            DatabasePlatform::PostgreSQL => 'id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            DatabasePlatform::MySQL => 'id INT AUTO_INCREMENT PRIMARY KEY',
            DatabasePlatform::SQLite => 'id INTEGER PRIMARY KEY AUTOINCREMENT',
        };
    }

    /** @infection-ignore-all MatchArmRemoval — only testable under the matching database platform */
    public function datetimeType(): string
    {
        return match ($this->platform) {
            DatabasePlatform::PostgreSQL => 'TIMESTAMP(0) WITHOUT TIME ZONE',
            DatabasePlatform::MySQL, DatabasePlatform::SQLite => 'DATETIME',
        };
    }

    /** @infection-ignore-all MatchArmRemoval — only testable under the matching database platform */
    public function extractDomain(string $column): string
    {
        return match ($this->platform) {
            DatabasePlatform::PostgreSQL => "SUBSTRING({$column} FROM '://([^/]+)')",
            DatabasePlatform::MySQL => "SUBSTRING_INDEX(SUBSTRING_INDEX({$column}, '://', -1), '/', 1)",
            DatabasePlatform::SQLite => "RTRIM(REPLACE(REPLACE({$column}, 'https://', ''), 'http://', ''), '/')",
        };
    }
}
